### ISSUE TITLE
Does not work on Python 3.4

### ISSUE THREAD

**Issue by ztane** [thruflo/pyramid_raven#1]
Just installed pyramid_raven, and found out it does not support Python 3.*, because it imports urllib directly; Also, the javascript injection is a bit unfortunate, as I am not using layout currently; was thinking that it would be nice to assign the js snippet to arbitrary key on the render dicts instead of using panels

**Comment by thruflo** [comment]
/me nods -- if you wanted to fix up the imports to work with Python 3 that would be great.

Re: rendering script tag, you could call the `raven_js_panel` function and pass the data and corresponding template spec to [pyramid.renderers.render](http://docs.pylonsproject.org/docs/pyramid/en/latest/api/renderers.html#pyramid.renderers.render) to get the template output as a string.

**Comment by miohtama** [comment]
Fixed in #2
